openapi: 3.0.1
info:
  title: Ukr-School-Books
  description: A plugin that allows the user to interact with a books database.
  version: 'v1'
servers:
  - url: https://ukr-books-chatgpt-plugin.illia56.repl.co
paths:

  /list_all/{grade}/{type}:
    post:
      operationId: listAll
      parameters:
      - in: path
        name: grade
        schema:
          type: string
        required: true
      - in: path
        name: type
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Returns a list of all books.
          
  /get_rnd/{grade}/{type}:
    post:
      operationId: getRnd
      parameters:
      - in: path
        name: grade
        schema:
          type: string
        required: true
      - in: path
        name: type
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Returns a random book.

  /get_books/{grade}/{type}/{author}:
    post:
      operationId: getBooks
      parameters:
      - in: path
        name: grade
        schema:
          type: string
        required: true
      - in: path
        name: type
        schema:
          type: string
        required: true
      - in: path
        name: type
        schema:
          type: author
        required: true
      responses:
        '200':
          description: Returns a list of all books for this author.

  /get_bio/{grade}/{type}/{author}:
    post:
      operationId: getBio
      parameters:
      - in: path
        name: grade
        schema:
          type: string
        required: true
      - in: path
        name: type
        schema:
          type: string
        required: true
      - in: path
        name: author
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Returns the biography of the author.

/get_content/{grade}/{type}/{author}:
    post:
      operationId: getContent
      parameters:
      - in: path
        name: grade
        schema:
          type: string
        required: true
      - in: path
        name: type
        schema:
          type: string
        required: true
      - in: path
        name: author
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Returns the content of the book.

